# Generated by Django 4.2.1 on 2023-07-28 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_alter_files_file_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_status', models.CharField(choices=[('Closed', 'Closed'), ('Limited', 'Limited'), ('Public', 'Public')], default='Closed', max_length=8)),
                ('blacklist', models.ManyToManyField(related_name='blacklist', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('whitelist', models.ManyToManyField(related_name='whitelist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
