# Generated by Django 4.2.1 on 2023-07-31 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='blacklist',
            field=models.ManyToManyField(blank=True, related_name='blacklist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='whitelist',
            field=models.ManyToManyField(blank=True, related_name='whitelist', to=settings.AUTH_USER_MODEL),
        ),
    ]
