# Generated by Django 4.2.1 on 2023-08-05 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_alter_userextended_blacklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='blacklist',
            field=models.ManyToManyField(related_name='file_blacklist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='files',
            name='whitelist',
            field=models.ManyToManyField(related_name='file_whitelist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='File_Acces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.files')),
            ],
        ),
    ]
