# Generated by Django 4.2.1 on 2023-08-05 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_files_blacklist_files_whitelist_file_acces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='blacklist',
            field=models.ManyToManyField(blank=True, related_name='file_blacklist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='files',
            name='whitelist',
            field=models.ManyToManyField(blank=True, related_name='file_whitelist', to=settings.AUTH_USER_MODEL),
        ),
    ]
