# Generated by Django 4.2.1 on 2023-08-05 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_files_blacklist_alter_files_whitelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='blacklist',
        ),
        migrations.RemoveField(
            model_name='files',
            name='whitelist',
        ),
    ]
