# Generated by Django 4.2.1 on 2023-08-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_files_blacklist_remove_files_whitelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
