# Generated by Django 4.1.1 on 2023-08-22 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('main', '0013_files_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='user',
        ),
        migrations.AlterField(
            model_name='file_acces',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='files.files'),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
